packages:
  - packages/*
  - test
  - website
catalog:
  "@ryoppippi/unplugin-typia": ^2.1.3
  "@samchon/openapi": ^3.2.3
  openai: ^4.80.0
  ts-patch: ^3.3.0
  typescript: ~5.8.2
  typia: ^8.1.1

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - typia
  - msw
