packages:
  - packages/*
  - benchmark/*
  - test
  - website
enablePrePostScripts: true
catalogs:
  libs:
    openai: ^4.80.0
    type-fest: ^4.37.0
  mcp:
    "@modelcontextprotocol/sdk": ^1.9.0
    "@wrtnlabs/calculator-mcp": ^0.2.1
  typescript:
    ts-patch: ^3.3.0
    typescript: ~5.8.3
  typia:
    "@ryoppippi/unplugin-typia": ^2.6.2
    "@samchon/openapi": ^4.3.0
    typia: ^9.3.0
  vite:
    vitest: ^3.0.9
onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - typia
  - msw
  - better-sqlite3
