packages:
  - packages/*
  - benchmark/*
  - test
  - website
enablePrePostScripts: true
useNodeVersion: 22.15.0
engineStrict: true
catalogs:
  libs:
    openai: ^6.15.0
    tstl: ^3.0.0
    type-fest: ^4.37.0
    uuid: ^13.0.0
  mcp:
    "@modelcontextprotocol/sdk": ^1.12.0
    "@wrtnlabs/calculator-mcp": ^0.2.1
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.9.3
  typia:
    "@ryoppippi/unplugin-typia": ^2.6.4
    "@samchon/openapi": ^6.0.1
    typia: ^11.0.3
  vite:
    vitest: ^3.0.9
onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - typia
  - msw
  - better-sqlite3
