packages:
  - packages/*
  - test
  - website

catalogs:
  libs:
    "@samchon/openapi": ^3.2.3
    openai: ^4.80.0
    typescript: ~5.8.2

  typia:
    "@ryoppippi/unplugin-typia": ^2.1.3
    ts-patch: ^3.3.0
    typia: ^8.1.1

  vite:
    vitest: ^3.0.9
onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - typia
  - msw
