import type { tags } from "typia";

/**
 * Base type for all histories in Agentica.
 *
 * `AgenticaHistoryBase` is a base type for every history types
 * in Agentica. It is generated by {@link Agentica.conversate} function,
 * and used for restoring the previous conversation history when
 * constructing the {@link Agentica} instance.
 *
 * @template Type Discriminator type
 * @template Json Primitive type of the history
 * @author Samchon
 */
export interface AgenticaHistoryBase<
  Type extends string,
  Json extends { type: Type },
> {
  /**
   * Primary key of the history.
   */
  id: string;

  /**
   * Discriminator type.
   */
  type: Type;

  /**
   * Creation timestamp of the history.
   */
  created_at: string & tags.Format<"date-time">;

  toJSON: () => Json;
}
