import type { IAgenticaConfigBase } from "./IAgenticaConfigBase";
import type { IMicroAgenticaExecutor } from "./IMicroAgenticaExecutor";
import type { IMicroAgenticaSystemPrompt } from "./IMicroAgenticaSystemPrompt";

/**
 * Configuration for Micro Agentic Agent.
 *
 * `INicroAgenticaConfig` is an interface that defines the configuration
 * properties of the {@link MicroAgentica}. With this configuration, you
 * can set the user's {@link locale}, {@link timezone}, and some of
 * {@link systemPrompt system prompts}.
 *
 * @author Samchon
 */
export interface IMicroAgenticaConfig extends IAgenticaConfigBase {
  /**
   * Agent executor.
   *
   * Executor function of Agentic AI's iteration plan to internal agents
   * running by the {@link Agentica.conversate} function.
   *
   * If you want to customize the agent execution plan, you can do it
   * by assigning you logic function of entire or partial to this property.
   * When customizing it, it would better to reference the
   * {@link ChatGptAgent.execute} function.
   *
   * @param ctx Context of the agent
   * @returns Lit of prompts generated by the executor
   * @default ChatGptAgent.execute
   */
  executor?:
    | undefined
    | Partial<IMicroAgenticaExecutor>;

  /**
   * System prompt messages.
   *
   * System prompt messages if you want to customize the system prompt
   * messages for each situation.
   */
  systemPrompt?: IMicroAgenticaSystemPrompt;

  /**
   * Whether to throw an exception when execution fails.
   *
   * If you set this property to `true` or define nothing, the A.I. chatbot
   * will throw an exception when {@link AgenticaExecuteHistory.success} is
   * `false`.
   *
   * Otherwise, the execution failure will be handled silently without
   * throwing an exception.
   *
   * @default true
   */
  throw?: boolean;
}
