/**
 * Base type for all prompts in Agentica.
 *
 * `AgenticaPromptBase` is a base type for every prompt types
 * in Agentica. It is generated by {@link Agentica.conversate} function,
 * and used for restoring the previous conversation history when
 * constructing the {@link Agentica} instance.
 *
 * @template Type Discriminator type
 * @template Json Primitive type of the prompt
 * @author Samchon
 */
export interface AgenticaPromptBase<
  Type extends string,
  Json extends { type: Type },
> {
  /**
   * Discriminator type.
   */
  type: Type;

  toJSON: () => Json;
}
