/**
 * Base class for all prompts in Agentica.
 *
 * `AgenticaPromptBase` is a base class for every prompt classes
 * in Agentica. It is generated by {@link Agentica.conversate} function,
 * and used for restoring the previous conversation history when
 * constructing the {@link Agentica} instance.
 *
 * @template Type Discriminator type
 * @template Json Primitive type of the prompt
 * @author Samchon
 */
export abstract class AgenticaPromptBase<
  Type extends string,
  Json extends { type: Type },
> {
  /**
   * Discriminator type.
   */
  public readonly type: Type;

  protected constructor(type: Type) {
    this.type = type;
  }

  public abstract toJSON(): Json;
}
