name: test
on:
  pull_request:
    paths:
      - 'packages/*/src/**'
      - 'test/**'
      - 'package.json'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm start
        working-directory: ./test
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}

