name: website
on: 
  push: 
    branches:
      - main
    paths:
      - 'packages/*/src/**'
      - 'website/**'
      - 'package.json'
      - .github/workflows/website.yml
  pull_request:
    paths:
      - 'packages/*/src/**'
      - 'website/**'
      - 'package.json'
      - '.github/workflows/website.yml'
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v2
      - name: Root
        run: pnpm install --frozen-lockfile
      - name: Website
        run: pnpm run build
        working-directory: website
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./website/out
