name: website
on: 
  push: 
    branches:
      - main
    paths:
      - 'packages/*/src/**'
      - 'website/**'
      - 'package.json'
      - .github/workflows/website.yml
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build TypeDoc
        run: node website/build/typedoc.js
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./website/public